### ISSUE TITLE
compatibility with "GENERATED ALWAYS" columns

### ISSUE THREAD

**Issue by yeoldegrove** [rheinwerk-verlag/pganonymize#51]
It would be great to have compatibility with https://www.postgresql.org/docs/current/ddl-generated-columns.html.
At the moment, when I name a generated column in the yml file, I get the following error:

```
- members:
    primary_key: uuid
    chunk_size: 5000
    fields:
     - name:
        provider:
          name: md5
     - firstname:
        provider:
          name: fake.first_name
     - lastname:
        provider:
          name: fake.last_name

psycopg2.errors.GeneratedAlways: column "name" can only be updated to DEFAULT
DETAIL:  Column "name" is a generated column.
```

This is of course, because generated columns can only be updated in a certain way.
Maybe a `generated` provider would be a nice addition?
